services:
  mongo:
    build: ./mongo/
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ~/temp:/data/db  
  graphql:
    build: ./graphql/
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb://192.168.50.101:27017/
    restart: on-failure
    depends_on:
      - mongo
    links:
      - mongo
